name: final_flashcard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # Network
  retrofit: ^4.0.3
  dio: ^5.4.0
  logger: ^2.0.2+1
  dio_cache_interceptor: ^3.5.0

  #Dependency Injection
  get: ^4.6.6
  get_it: ^7.6.4
  injectable: ^2.3.2

  #State Management
  flutter_bloc: ^8.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  equatable: ^2.0.5

  #UI
  after_layout: ^1.2.0
  intl: ^0.18.1
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.6.0
  awesome_dialog: ^3.2.0
  flutter_inappwebview: ^6.0.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  gap: ^3.0.1
  image_picker: ^1.0.7
  flip_card: ^0.7.0
  flutter_card_swiper: ^7.0.1

  #Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8

  #Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Utils
  change_app_package_name: ^1.1.0
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  avatar_glow: ^3.0.1
  path_provider: ^2.1.3
  flutter_tts: ^4.0.2
  rxdart: ^0.27.7
  connectivity_plus: ^6.0.3
  file_picker: ^8.0.0+1
  csv: ^6.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  open_file_plus: ^3.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7
  analyzer: ^6.2.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/