// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVvBnW3_j_glDjM_g1GzQ-L9aRkKJH-7U',
    appId: '1:197945533961:web:f7a19fe0b6cfe980763ad8',
    messagingSenderId: '197945533961',
    projectId: 'flutter-flashcards-45aca',
    authDomain: 'flutter-flashcards-45aca.firebaseapp.com',
    storageBucket: 'flutter-flashcards-45aca.appspot.com',
    measurementId: 'G-QT8SZS7MM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCB6PxL-9ZadlsbGIHKEuoi6l_c6LquFE',
    appId: '1:197945533961:android:c02b21114a95a677763ad8',
    messagingSenderId: '197945533961',
    projectId: 'flutter-flashcards-45aca',
    storageBucket: 'flutter-flashcards-45aca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZ9thKIpPExy9b9L0yoAFIE5P7EYVyZs',
    appId: '1:197945533961:ios:4dcf8dceb8b002e5763ad8',
    messagingSenderId: '197945533961',
    projectId: 'flutter-flashcards-45aca',
    storageBucket: 'flutter-flashcards-45aca.appspot.com',
    iosBundleId: 'com.example.finalFlashcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVZ9thKIpPExy9b9L0yoAFIE5P7EYVyZs',
    appId: '1:197945533961:ios:7058fc4c809b7b4f763ad8',
    messagingSenderId: '197945533961',
    projectId: 'flutter-flashcards-45aca',
    storageBucket: 'flutter-flashcards-45aca.appspot.com',
    iosBundleId: 'com.example.finalFlashcard.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVvBnW3_j_glDjM_g1GzQ-L9aRkKJH-7U',
    appId: '1:197945533961:web:d5920838ececaf98763ad8',
    messagingSenderId: '197945533961',
    projectId: 'flutter-flashcards-45aca',
    authDomain: 'flutter-flashcards-45aca.firebaseapp.com',
    storageBucket: 'flutter-flashcards-45aca.appspot.com',
    measurementId: 'G-V65L64XSWR',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAVvBnW3_j_glDjM_g1GzQ-L9aRkKJH-7U',
    appId: '1:197945533961:web:506029cb9b8c842a763ad8',
    messagingSenderId: '197945533961',
    projectId: 'flutter-flashcards-45aca',
    authDomain: 'flutter-flashcards-45aca.firebaseapp.com',
    storageBucket: 'flutter-flashcards-45aca.appspot.com',
    measurementId: 'G-X8PTBGYP4E',
  );
}
